language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run generate
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "zilpay-test"
after_success:
  - 