language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run generate
deploy:
  provider: firebase
  token:
    secure: $ENCRYPTED_TOKEN
  project: zilpay-test
  on:
    branch: master